apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: ai-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: ai-gateway-billing-service:lab6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ai-gateway-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: ai-gateway-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ai-gateway-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ai-gateway-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: ai-gateway-config
                  key: BILLING_DB_NAME
            - name: DB_SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: ai-gateway-config
                  key: DB_SSLMODE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ai-gateway-secret
                  key: JWT_SECRET
            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ai-gateway-secret
                  key: INTERNAL_SERVICE_TOKEN
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
