apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: ai-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: ai-gateway-gateway-service:lab6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ai-gateway-secret
                  key: JWT_SECRET
            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ai-gateway-secret
                  key: INTERNAL_SERVICE_TOKEN
            - name: BILLING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ai-gateway-config
                  key: BILLING_SERVICE_URL
            - name: TASK_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ai-gateway-config
                  key: TASK_SERVICE_URL
            - name: FRONTEND_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: ai-gateway-config
                  key: FRONTEND_ORIGIN
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
